### ISSUE TITLE
invalid file read still marked as success

### ISSUE THREAD

**Issue by thomasdupas** [dblacka/jdnssec-tools#19]
When pointing jdnssec-verifyzone version 0.20 to a non-existent file (or file it can't read) it still marks it as a success.
With 0.15 we didn't experience this, didn't test intermediate versions yet to see as of which version it started

```
$ jdnssec-verifyzone -v 2 /tmp/non-existent
FINE: Unable to load BC provider
java.io.FileNotFoundException: 2 (No such file or directory)
        at java.base/java.io.FileInputStream.open0(Native Method)
        at java.base/java.io.FileInputStream.open(FileInputStream.java:216)
        at java.base/java.io.FileInputStream.<init>(FileInputStream.java:157)
        at org.xbill.DNS.Tokenizer.<init>(Tokenizer.java:187)
        at org.xbill.DNS.Master.<init>(Master.java:44)
        at org.xbill.DNS.Master.<init>(Master.java:69)
        at com.verisignlabs.dnssec.security.ZoneUtils.readZoneFile(ZoneUtils.java:61)
        at com.verisignlabs.dnssec.cl.VerifyZone.execute(VerifyZone.java:103)
        at com.verisignlabs.dnssec.cl.CLBase.run(CLBase.java:400)
        at com.verisignlabs.dnssec.cl.VerifyZone.main(VerifyZone.java:121)
FINE: verifying zone...
INFO: Zone null verified with 0 errors
FINE: completed verification process.
zone verified.
$ echo $?
0
```

**Comment by dblacka** [comment]
I'm assuming that we lost the correct failure behavior in my largish refactoring around going to dnsjava 3.x.  I'll have an update that fixes it shortly.
