### ISSUE TITLE
jdnssec verify can not handle CAA records

### ISSUE THREAD

**Issue by SvenVD-be** [dblacka/jdnssec-tools#9]
org.xbill.DNS.Tokenizer$TokenizerException: dns.be.zone.forfast.axfr:30: Invalid type 'CAA'
	at org.xbill.DNS.Tokenizer.exception(Tokenizer.java:710)
	at org.xbill.DNS.Master.parseTTLClassAndType(Master.java:161)
	at org.xbill.DNS.Master._nextRecord(Master.java:364)
	at org.xbill.DNS.Master.nextRecord(Master.java:388)
	at com.verisignlabs.dnssec.security.ZoneUtils.readZoneFile(ZoneUtils.java:74)
	at com.verisignlabs.dnssec.cl.VerifyZone.execute(VerifyZone.java:141)
	at com.verisignlabs.dnssec.cl.CLBase.run(CLBase.java:336)
	at com.verisignlabs.dnssec.cl.VerifyZone.main(VerifyZone.java:164)

version jdnssec-tools-0.14-0

**Comment by dblacka** [comment]
0.14 had a version of dnsjava.jar without a CAA implementation.  This was odd because the version number matched what we had in jdnssec-dnsjava, and that did have an implementation.  Updating the jar fixes this issue.
